//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remont_Kursovoi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Журнал_выполненных_ремонтов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Журнал_выполненных_ремонтов()
        {
            this.Работник_в_ремонте = new HashSet<Работник_в_ремонте>();
        }

        public System.Guid ID_ремонта { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Дата_начала { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Дата_окончания { get; set; }
        public Nullable<System.Guid> ID_планового_ремонта { get; set; }
        public int Код_экземпляра { get; set; }
        public Nullable<int> Код_ремонта { get; set; }
        [StringLength(100, ErrorMessage = "Примечание должно содержать не более 100 символов")]
        public string Примечания { get; set; }


        public virtual График_плановых_техобслуживаний График_плановых_техобслуживаний { get; set; }
        public virtual Экземпляры_оборудований Экземпляры_оборудований { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работник_в_ремонте> Работник_в_ремонте { get; set; }
        public virtual Типы_ремонта Типы_ремонта { get; set; }
    }
}
