//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remont_Kursovoi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Работники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Работники()
        {
            this.График_плановых_техобслуживаний = new HashSet<График_плановых_техобслуживаний>();
            this.Работник_в_ремонте = new HashSet<Работник_в_ремонте>();
        }

        public System.Guid ID_работника { get; set; }
        [StringLength(50, ErrorMessage = "Должность должна быть не более 50 символов")]
        public string Должность { get; set; }
        [StringLength(50, ErrorMessage = "Фамилия должна быть не более 50 символов")]
        public string Фамилия { get; set; }
        [StringLength(50, ErrorMessage = "Имя должно быть не более 50 символов")]
        public string Имя { get; set; }
        [StringLength(50, ErrorMessage = "Отчество должно быть не более 50 символов")]
        public string Отчество { get; set; }
        [StringLength(50, ErrorMessage = "Логин должен быть не более 50 символов")]
        public string Логин { get; set; }
        [DataType(DataType.Password)]
        [StringLength(50, ErrorMessage = "Пароль должен быть не более 50 символов")]

        public string Пароль { get; set; }
        public Nullable<int> Соль { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<График_плановых_техобслуживаний> График_плановых_техобслуживаний { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работник_в_ремонте> Работник_в_ремонте { get; set; }
    }
}
