//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remont_Kursovoi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Типы_оборудования
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Типы_оборудования()
        {
            this.Экземпляры_оборудований = new HashSet<Экземпляры_оборудований>();
            this.Типы_ремонта = new HashSet<Типы_ремонта>();
        }
    
        public System.Guid ID_типа_оборудования { get; set; }
        [StringLength(50, ErrorMessage = "Тип должен быть не более 50 символов")]
        public string Наименование_типа { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Экземпляры_оборудований> Экземпляры_оборудований { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Типы_ремонта> Типы_ремонта { get; set; }
    }
}
